module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        mobile: "320px",
        tablet: "768px",
        desktop: "1024px",
      },
      colors: {
        "text-primary": "var(--color-grey-grey-900)",
        "text-secondary": "var(--color-grey-grey-500)",
        "text-note": "var(--color-grey-grey-300)",
        "text-invert": "var(--color-grey-grey-50)",
        "text-brand": "var(--color-brand-brand-purple-500)",
        "text-success": "var(--color-state-safe)",
        "text-warning": "var(--color-state-warn)",
        "text-error": "var(--color-state-danger)",
        "surface-background": "var(--color-grey-grey-50)",
        "surface-primary": "var(--color-grey-grey-000)",
        "surface-secondary": "var(--color-grey-grey-100)",
        "surface-invert": "var(--color-grey-grey-900)",
        "surface-brand": "var(--color-brand-brand-purple-500)",
        "button-primary": "var(--color-brand-brand-purple-500)",
        "button-secondary": "var(--color-grey-grey-600)",
        "button-accent": "var(--color-brand-brand-blud-500)",
        "button-disable": "var(--color-grey-grey-300)",
        "button-primary-hover": "var(--color-brand-brand-purple-300)",
        "button-secondary-hover": "var(--color-grey-grey-500)",
        "button-accent-hover": "var(--color-brand-brand-blud-300)",
        link: "var(--color-state-link)",
        "link-hover": "var(--color-state-link--hover)",
        "border-primary": "var(--color-grey-grey-900)",
        "border-secondary": "var(--color-grey-grey-300)",
        "border-brand": "var(--color-brand-brand-purple-500)",
        "border-success": "var(--color-state-safe)",
        "border-warning": "var(--color-state-warn)",
        "border-error": "var(--color-state-danger)",
      },
      spacing: {
        "spacing-none": "0px",
        "spacing-3xs": "var(--spacing-1)",
        "spacing-2xs": "var(--spacing-2)",
        "spacing-xs": "var(--spacing-3)",
        "spacing-s": "var(--spacing-4)",
        "spacing-m": "var(--spacing-5)",
        "spacing-l": "var(--spacing-6)",
        "spacing-xl": "var(--spacing-7)",
        "spacing-2xl": "var(--spacing-8)",
        "spacing-3xl": "var(--spacing-9)",
        "spacing-4xl": "var(--spacing-10)",
      },
      borderRadius: {
        "radius-none": "0px",
        "radius-xs": "var(--radius-1)",
        "radius-s": "var(--radius-2)",
        "radius-m": "var(--radius-3)",
        "radius-l": "var(--radius-4)",
        "radius-rounded": "var(--radius-5)",
      },
    },
  },
};
